version: '3'
services:
  bot1:
    build: .
    container_name: bot1-container
    environment:
      - BOT_TOKEN=your_bot1_token
    ports:
      - "8081:8080"
    restart: always
  bot2:
    build: .
    container_name: bot2-container
    environment:
      - BOT_TOKEN=your_bot2_token
    ports:
      - "8082:8080"
    restart: always
